boostcampwm-2021/android07-notto

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/gojol/notto/NottoApplication.kt
- app/src/main/java/com/gojol/notto/model/data/Label.kt
- app/src/main/java/com/gojol/notto/model/data/RepeatType.kt
- app/src/main/java/com/gojol/notto/model/data/Todo.kt
- app/src/main/java/com/gojol/notto/model/datasource/option/OptionRepository.kt
- app/src/main/java/com/gojol/notto/model/datasource/popular/PopularRepository.kt
- app/src/main/java/com/gojol/notto/model/datasource/todo/TodoRepository.kt
- app/src/main/java/com/gojol/notto/ui/MainActivity.kt
> [demo_week2] Repository 패키지 구조, Todo, Label 데이터 구조 설계

- app/src/main/java/com/gojol/notto/model/database/TodoLabelDatabase.kt
- app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelDataSource.kt
- app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
> [demo_week2] TodoLabel 인터페이스 구성

- app/build.gradle
- app/src/main/java/com/gojol/notto/NottoApplication.kt
- app/src/main/java/com/gojol/notto/di/TodoLabelDatabaseModule.kt
- app/src/main/java/com/gojol/notto/model/database/TodoLabelDatabase.kt
- app/src/main/java/com/gojol/notto/model/database/todolabel/TodoLabelDao.kt
- app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelDataSource.kt
- app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
- app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
- app/src/main/java/com/gojol/notto/ui/MainActivity.kt
- app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
- app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_option.xml
- app/src/main/res/layout/fragment_popular.xml
> [demo_week2] TodoLabelRepository 구현 및 의존성 주입

- app/src/main/java/com/gojol/notto/ui/home/Dummy.kt
- app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
- app/src/main/java/com/gojol/notto/ui/home/LabelAdapter.kt
- app/src/main/java/com/gojol/notto/ui/home/LabelWithCheck.kt
https://user-images.githubusercontent.com/64943924/140251182-85f15995-da16-4bc2-8a22-dd5a3e59be75.mp4
- #29
> [demo_week2] 라벨 관련 데이터타입 추가, 라벨 필터링 로직 구현

- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/item_label.xml
- app/src/main/res/layout/item_label_list.xml
|![image](https://user-images.githubusercontent.com/64943924/140314057-96c6070f-735d-4a4a-93fc-98d46caa2b56.png)|![image](https://user-images.githubusercontent.com/64943924/140314073-d381bcc3-34ac-4a50-9ec3-8195ec6935d7.png)|
|---|---|
- #3
> #3 [fix] home 관련 레이아웃 디자인 수정

- app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
- app/src/main/res/layout/item_todo.xml
> [demo_week2] 발표용  - 더미 데이터 생성 및 사소한 디자인 수정

- app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
- app/src/main/java/com/gojol/notto/ui/home/adapter/TodoAdapter.kt
- app/src/main/java/com/gojol/notto/ui/home/util/ItemTouchHelperListener.kt
- app/src/main/java/com/gojol/notto/ui/home/util/TodoItemTouchCallback.kt
- app/src/main/res/layout/item_todo.xml
https://user-images.githubusercontent.com/64943924/140696167-29472093-ad3c-4eef-9374-20a9083b7d16.mp4
- #32
> [demo_week3] Todo 관련 리팩토링, 스와이프 취소 구현, 텍스트 색상과 크기 변경

- app/src/main/res/drawable/ic_add.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/values/dimens.xml
https://user-images.githubusercontent.com/55148494/140863980-849ca838-0b5d-4ef5-8d9c-31a38c1d662e.mp4
- #3
> [demo_week3] Home 화면에 Todo 추가 버튼 추가

- app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
- app/src/main/java/com/gojol/notto/ui/label/EditLabelViewModel.kt
https://user-images.githubusercontent.com/39328846/141319148-6f64db98-bdaf-4693-b8c3-9e8188dd1c78.mp4
> [demo_week3] 라벨 편집 화면에서 '전체' 라벨 제외

- app/src/main/java/com/gojol/notto/util/Extensions.kt
> [demo_week3] date 포멧 관련 버그 수정

- app/src/main/java/com/gojol/notto/ui/label/EditLabelViewModel.kt
> [demo_week3] 라벨 초기화 코드 추가

- app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
- app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
- app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoAlarmPeriodDialog.kt
- app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoBaseDialog.kt
- app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoBaseDialogImpl.kt
- app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoDeletionDialog.kt
- app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTimeDialog.kt
- app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTypeDialog.kt
- app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoSetTimeDialog.kt
- app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TodoBaseDialog.kt
- app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TodoBaseDialogViewModel.kt
- app/src/main/java/com/gojol/notto/util/Extensions.kt
- app/src/main/java/com/gojol/notto/util/TouchEvent.kt
- app/src/main/res/layout/dialog_base.xml
- app/src/main/res/layout/dialog_deletion.xml
- app/src/main/res/layout/dialog_todo_alarm_period.xml
- app/src/main/res/layout/dialog_todo_repeat_time.xml
- app/src/main/res/layout/dialog_todo_repeat_type.xml
- app/src/main/res/layout/dialog_todo_set_time.xml
https://user-images.githubusercontent.com/26290540/141709092-9b370122-661c-477e-9aee-1e2ab7f2fb05.mp4
> [demo_week3] 다이얼로그 구조 수정

- app/build.gradle
- app/src/main/java/com/gojol/notto/NottoApplication.kt
> [demo_week4] stetho 적용

- app/build.gradle
- app/src/main/java/com/gojol/notto/common/Constants.kt
- app/src/main/java/com/gojol/notto/ui/label/EditLabelActivity.kt
- app/src/main/java/com/gojol/notto/ui/label/EditLabelAdapter.kt
- app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogFragment.kt
- app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogFragment.kt
https://user-images.githubusercontent.com/39328846/141968816-b62628b5-9e2c-4bf1-885f-2ff4df4602f6.mp4
> [demo_week4] 라벨 편집 화면 Dialog 버그 수정

- app/build.gradle
- app/src/main/java/com/gojol/notto/util/Extensions.kt
- app/src/main/res/layout/item_label.xml
- app/src/main/res/values/strings.xml
> [demo_week4] 라벨 간격 버그 수정

- app/src/main/java/com/gojol/notto/ui/home/CalendarFragment.kt
- app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
- app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarAdapter.kt
- app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarViewPagerAdapter.kt
https://user-images.githubusercontent.com/64943924/142366255-0b813657-3c62-4157-95b3-69b08020ef44.mp4
- #11
> [demo_week4] 캘린더와 홈 Fragment 간의 데이터 통신 구현 (깜박임 현상 해결)

- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/item_label_list.xml
- app/src/main/res/layout/item_todo.xml
- app/src/main/res/values/dimens.xml
https://user-images.githubusercontent.com/39328846/142398903-01542f00-7d78-417e-9761-053becfd9b21.mp4
> [demo_week4] 스크롤, 스와이프 시 바깥 영역을 사용하도록 변경

- .gitignore
- app/src/main/java/com/gojol/notto/di/TodoLabelDatabaseModule.kt
- app/src/main/java/com/gojol/notto/model/database/TodoLabelDatabase.kt
> [develop] gitignore에 firebase key 파일 추가, db migration 설정

- app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManager.kt
- app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManagerImpl.kt
- app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
- app/src/main/java/com/gojol/notto/util/SuccessButtonWorker.kt
- app/src/main/java/com/gojol/notto/util/TodoPushBroadcastReceiver.kt
- app/src/main/java/com/gojol/notto/util/TodoSuccessCheckBroadcastReceiver.kt
> [develop] Todo 푸시 알림 리팩토링

- app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
> [develop] swipe 깜빡임 버그 수정

- app/src/main/res/drawable/ic_info.xml
- app/src/main/res/layout/fragment_option.xml
- app/src/main/res/values/strings.xml
> [develop] Option 화면 하루 마무리 알림 설명 추가

- app/src/main/java/com/gojol/notto/ui/home/CalendarViewModel.kt
> [develop] 캘린더 refresh, 날짜 select 로직 수정

- app/src/main/java/com/gojol/notto/ui/home/calendar/CalendarFragment.kt
> [develop] 캘린더 fragment에서 캐스팅 오류 수정

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/gojol/notto/common/Constants.kt
- app/src/main/java/com/gojol/notto/di/OptionModule.kt
- app/src/main/java/com/gojol/notto/model/datasource/option/OptionDataSource.kt
- app/src/main/java/com/gojol/notto/model/datasource/option/OptionLocalDataSource.kt
- app/src/main/java/com/gojol/notto/model/datasource/option/OptionRemoteDataSource.kt
- app/src/main/java/com/gojol/notto/model/datasource/option/OptionRepository.kt
- app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
- app/src/main/java/com/gojol/notto/network/GithubResponse.kt
- app/src/main/java/com/gojol/notto/network/GithubService.kt
- app/src/main/java/com/gojol/notto/ui/option/ContributorActivity.kt
- app/src/main/java/com/gojol/notto/ui/option/ContributorAdapter.kt
- app/src/main/java/com/gojol/notto/ui/option/OptionFragment.kt
- app/src/main/java/com/gojol/notto/ui/option/OptionViewModel.kt
- app/src/main/java/com/gojol/notto/util/NetworkState.kt
- app/src/main/java/network/GithubResponse.kt
- app/src/main/java/network/GithubService.kt
- app/src/main/res/layout/activity_contributor.xml
- app/src/main/res/layout/fragment_option.xml
- app/src/main/res/layout/item_contributor.xml
- app/src/main/res/values/strings.xml
- build.gradle
https://user-images.githubusercontent.com/55148494/143969969-25e124df-d3a6-48e7-9fbe-7156f0e098df.mp4
- #19 
- #214
> [develop] Option 화면 버그 수정 및 Contributors 추가

- app/src/main/java/com/gojol/notto/common/Constants.kt
- app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
- app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
- app/src/main/java/com/gojol/notto/ui/todo/dialog/RepeatTimeDialog.kt
- app/src/main/java/com/gojol/notto/util/TodoSuccessCheckBroadcastReceiver.kt
https://user-images.githubusercontent.com/26290540/144379298-d270a73b-1d62-4a74-b4ea-7e9e25a73567.mov
> [develop] 알림 성공/실패 버튼 터치 시 UI 동기화

- app/src/main/res/values-night/themes.xml
> [develop] 다크모드 디자인 수정

- app/build.gradle
> [develop] 버전 업그레이드

- app/build.gradle
- app/src/main/java/com/gojol/notto/ui/home/calendar/CalendarFragment.kt
> [demo_week6] 버전 업그레이드

- app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogFragment.kt
- app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogViewModel.kt
- app/src/main/res/layout/dialog_fragment_edit_label.xml
- app/src/main/res/values/strings.xml
https://user-images.githubusercontent.com/39328846/144697836-edf4d300-05a3-4339-9d71-1d96b6dd32b8.mp4
> [develop] 중복 라벨 처리

- app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogViewModel.kt
> [develop] 라벨 삭제 후 라벨 생성 시 순서가 꼬이는 버그 해결

- app/src/main/res/layout/activity_todo_edit.xml
- app/src/main/res/layout/item_label_list.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
> [develop] 일부 버튼에 다크 테마 적용

- app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
- app/src/main/java/com/gojol/notto/ui/home/adapter/LabelWrapperAdapter.kt
- app/src/main/java/com/gojol/notto/ui/home/calendar/CalendarFragment.kt
- app/src/main/java/com/gojol/notto/ui/home/calendar/adapter/CalendarDayAdapter.kt
- app/src/main/java/com/gojol/notto/ui/home/calendar/adapter/CalendarViewPagerAdapter.kt
> [develop] 캘린더 리사이클러뷰 재활용, 라벨 스크롤위치 save & restore
